// <auto-generated />
using System;
using CodeFirst.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace CodeFirst.API.Migrations.Cart
{
    [DbContext(typeof(CartContext))]
    [Migration("20190203171143_CartContextUpdated")]
    partial class CartContextUpdated
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.1-servicing-10028")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("CodeFirst.Models.Cart", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CreatedDate");

                    b.Property<string>("Description");

                    b.Property<int>("Price");

                    b.Property<string>("Title");

                    b.HasKey("Id");

                    b.ToTable("Carts");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedDate = new DateTime(2019, 2, 3, 17, 11, 42, 84, DateTimeKind.Utc).AddTicks(4642),
                            Description = "Casual shopping",
                            Price = 100,
                            Title = "1 week buy shopping"
                        },
                        new
                        {
                            Id = 2,
                            CreatedDate = new DateTime(2019, 2, 3, 17, 11, 42, 84, DateTimeKind.Utc).AddTicks(9347),
                            Description = "Mid week shopping",
                            Price = 50,
                            Title = "Buying some good stuff"
                        });
                });

            modelBuilder.Entity("CodeFirst.Models.CartItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Calories");

                    b.Property<int>("CartId");

                    b.Property<string>("Description");

                    b.Property<DateTime>("ExpirationDate");

                    b.Property<int>("Fats");

                    b.Property<string>("Name");

                    b.Property<int>("Proteins");

                    b.Property<DateTime>("PurchaseDate");

                    b.Property<int>("Sacharides");

                    b.Property<int>("Weight");

                    b.HasKey("Id");

                    b.HasIndex("CartId");

                    b.ToTable("CartItem");
                });

            modelBuilder.Entity("CodeFirst.Models.CartItem", b =>
                {
                    b.HasOne("CodeFirst.Models.Cart")
                        .WithMany("CartItems")
                        .HasForeignKey("CartId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
