// <auto-generated />
using System;
using CodeFirst.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace CodeFirst.API.Migrations
{
    [DbContext(typeof(CartItemContext))]
    partial class CartItemContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.1-servicing-10028")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("CodeFirst.Models.CartItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Calories");

                    b.Property<int>("CartId");

                    b.Property<string>("Description");

                    b.Property<DateTime>("ExpirationDate");

                    b.Property<int>("Fats");

                    b.Property<string>("Name");

                    b.Property<int>("Proteins");

                    b.Property<DateTime>("PurchaseDate");

                    b.Property<int>("Sacharides");

                    b.Property<int>("Weight");

                    b.HasKey("Id");

                    b.ToTable("CartItems");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Calories = 150,
                            CartId = 0,
                            Description = "Cheat day",
                            ExpirationDate = new DateTime(2019, 2, 13, 17, 12, 18, 662, DateTimeKind.Utc).AddTicks(8014),
                            Fats = 100,
                            Name = "Snack",
                            Proteins = 100,
                            PurchaseDate = new DateTime(2019, 2, 3, 17, 12, 18, 662, DateTimeKind.Utc).AddTicks(7135),
                            Sacharides = 100,
                            Weight = 100
                        },
                        new
                        {
                            Id = 2,
                            Calories = 333,
                            CartId = 0,
                            Description = "xxx",
                            ExpirationDate = new DateTime(2019, 2, 13, 17, 12, 18, 662, DateTimeKind.Utc).AddTicks(8972),
                            Fats = 111,
                            Name = "Healthy",
                            Proteins = 222,
                            PurchaseDate = new DateTime(2019, 2, 3, 17, 12, 18, 662, DateTimeKind.Utc).AddTicks(8969),
                            Sacharides = 333,
                            Weight = 222
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
